version: "3"
services:
  nodejs:
    image: node:14
    container_name: nodejs
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3030:3030
    command: "npm run start"
    tty: true
    links:
      - mongodb
    networks:
      - webnet
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod
    networks:
      - webnet

networks:
  webnet:

volumes:
 mongodb: